### ISSUE TITLE
Bounding box excludes pixc latitudes > 180 (but not when lat/lon have missing values)

### ISSUE THREAD

**Issue by markwh** [SWOTAlgorithms/RiverObs#19]
I think there are 2 issues here. One is that shifting bounding box latitudes to [-180, 180] excludes pixc points with latitude > 180, as in the Sacramento pixc (all points). 

I'm pretty sure this is because `self.lon` is shifted `-=360` after it has already been assigned using the default `index = True` ([see here](https://github.com/SWOTAlgorithms/RiverObs/blob/20d774188fef7375ca2c2454319f842e8ab9d303/src/SWOTRiver/SWOTL2.py#L86))

Curiously, if I don't supply a `--gdem-file` (in swot_pixc2rivertile.py) the bounding box isn't applied. I think this may be because the bounding box can't be created properly due to missing (nan) values in the Sacramento pixel cloud's latitude. I can verify that `np.max(self.get(lat_kwd, use_index = False))` is `nan` only when I don't supply `--gdem-file`, and (just when `--gdem-file` is not supplied) I get warnings looking like this:

````
C:\...\RiverObs\src\SWOTRiver\SWOTL2.py:174: RuntimeWarning: invalid value encountered in less_equal
  (lat <= self.latmax) & (lon <= self.lonmax))
C:\...\RiverObs\src\SWOTRiver\SWOTL2.py:204: UserWarning: WARNING: valid_max not used since it
cannot be safely cast to variable data type
  data = self.nc.groups['pixel_cloud'][var][:]
````

When I supply a gdem I do not get these warnings, just the error `Exception: number of good points: 0 smaller than required: 100`.

**Comment by alexfore** [comment]
* self.set_index_and_bounding_box wraps lon into [-180, 180) interval so it can compute the self.index used to subset the input data (pixel cloud or fake pixel cloud).
* self.lon is assigned after the call to self.set_index_and_bounding_box, then wrapped into same interval after being subset by self.index in get method.
* each wraps lon into [-180, 180) interval (or that is what is intended)
* bbox is also wrapped into that interval by SWOTRiver.Estimate class before instantiation of SWOTRiverEstimator class (which inherits from SWOTL2)

I don't see any problems with that.  

On to warnings:
* The first warning seems to come from NaNs are really due to a problem in the input data (simulated pixel cloud data).  Any logical comparisons to NaN yield false, thus they don't cause an error (are rejected from the bounding box intersection that goes into self.index).

* The second warning is actually another problem with the pixel cloud. the valid_min/max for latitude appear to int64 types where they should have the same type as the dataset.

Nothing to fix in RiverObs for either of these things either.

It all works fine on the SAC case here; so I think it is your netcdf4 package:
What is output of ```conda list netcdf4```  There have been major changes in handling of MaskArray which cause all kinds of issues.  I'm using 1.4.1, recommend you use the same.

**Comment by markwh** [comment]
OK, it's sorted out. I was using the wrong rdf file specifications for using a gdem. So fwiw that's the error that comes up if you use the non-gdem class specifications in the rdf. Still getting a bunch of warnings like before, and like the one pasted below for the plot functions, but everything appears to work OK. 

```
 valid_max not used since it cannot be safely cast to variable data type
  variable = variable[:]
```
