### ISSUE TITLE
Compute enhanced slopes (SWOTRiverEstimator.py) and empty reach

### ISSUE THREAD

**Issue by DamienDesroches** [SWOTAlgorithms/RiverObs#6]
The function compute_enhanced_slopes (src/SWOTRiver/SWOTRiverEstimator.py) doesn't support empty reach.

**Comment by alexfore** [comment]
- what run script are you using?
- cut and paste the traceback
- minimal set of data for me to replicate the problem (input file, reach db if it is different from what we are using, riverobs config file)

But perhaps most importantly what is desired for empty reaches?  Discard them as soon as find out they are empty? I don't think we should keep them so I will probably try to remove them at the right place rather than change that method.

**Comment by DamienDesroches** [comment]
1.  I run through this script (wrapper from swot_hydrology_toolbox which run your swot_pixc2rivertile.py script) : 
python $SWOT_HYDROLOGY_TOOLBOX/scripts/l2pixc_to_rivertile.py output/simu/pixc_annotation_000_003_46N-R.rdf output/riverbug --parameter_riverobs rdf/parameter_river.rdf

2. The log looks like that : 
False
Dataset opened
Number of points in these classes: 774860
Number of points in bounding box: 774860
....
Reach 9/9 Reach index: 116602
Centerline initialized
...
reach pocessed
numNodes,k: 60 3
Observations added to nodes
reach pocessed
Traceback (most recent call last):
  File "/work/ALT/swot/swotdev/desrochesd/swot_hydrology_toolbox/RiverObs/src/bin/swot_pixc2rivertile.py", line 103, in <module>
    main()
  File "/work/ALT/swot/swotdev/desrochesd/swot_hydrology_toolbox/RiverObs/src/bin/swot_pixc2rivertile.py", line 78, in main
    l2pixc_to_rivertile.do_river_processing()
  File "/work/ALT/swot/swotdev/desrochesd/swot_hydrology_toolbox/RiverObs/src/SWOTRiver/Estimate.py", line 109, in do_river_processing
    max_iter=self.config['max_iter'])
  File "/work/ALT/swot/swotdev/desrochesd/swot_hydrology_toolbox/RiverObs/src/SWOTRiver/SWOTRiverEstimator.py", line 495, in process_reaches
    enhanced=enhanced)
  File "/work/ALT/swot/swotdev/desrochesd/swot_hydrology_toolbox/RiverObs/src/SWOTRiver/SWOTRiverEstimator.py", line 1164, in compute_enhanced_slopes
    ind = [reach.reach_indx[0] for reach in river_reach_collection]
  File "/work/ALT/swot/swotdev/desrochesd/swot_hydrology_toolbox/RiverObs/src/SWOTRiver/SWOTRiverEstimator.py", line 1164, in <listcomp>
    ind = [reach.reach_indx[0] for reach in river_reach_collection]
IndexError: index 0 is out of bounds for axis 0 with size 0

3. For the dataset, it is more complicated. It is a scene on the Leman lake. I have different scènes from different orbit, an one of them is crashing (003_46N-5 orbit). The input data is quite big, I can zip it and send it to you. If you can connect on the CNES cluster, I can also give you the access to the pixel cloud  file (and to the rdf).

4. Concerning the empty reaches, I also think we should remove them as soon as possible in the code, and avoid to modify independently each function to deal with them.

**Comment by ruiwei33** [comment]
Hi Damien,

I’ve made some improvements for “compute_enhanced_slopes” at my fork. 

https://github.com/ruiwei33/RiverObs/blob/split-process-reaches/src/SWOTRiver/SWOTRiverEstimator.py

Please let me know if you have any questions.

Rui

**Comment by alexfore** [comment]
@DamienDesroches I think need to check if reach is empty (or None, not sure what it is when the issue happens) at:

https://github.com/SWOTAlgorithms/RiverObs/blob/develop/src/SWOTRiver/SWOTRiverEstimator.py#L1192

If it is empty or None or fault case do:
```
enhanced_slopes.append(None)
```
since other code assumes it is a list with same length as the river_reach_collection in the code that calls compute_enhanced_slopes.  You can prob fix it yourself if use python debugger to see how to test for fault case.
